#!/usr/bin/env bash
# GitHub Actions Quick Reference for SOS App
# Run this file for a quick overview: chmod +x GITHUB_ACTIONS_QUICK_REF.sh && ./GITHUB_ACTIONS_QUICK_REF.sh

echo "╔════════════════════════════════════════════════════════════════╗"
echo "║   SOS App - GitHub Actions CI/CD Quick Reference              ║"
echo "╚════════════════════════════════════════════════════════════════╝"
echo ""

echo "📋 WORKFLOWS SUMMARY"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "1. CI Pipeline (ci.yml)"
echo "   Trigger: Push/PR to master/main/develop"
echo "   Jobs: Lint → Test → APK Build"
echo "   Duration: ~40-50 minutes"
echo ""
echo "2. Code Quality (code-quality.yml)"
echo "   Trigger: Push/PR + Weekly (Mondays)"
echo "   Jobs: Dependency scan, Type check"
echo "   Duration: ~10-15 minutes"
echo ""
echo "3. Release (release.yml)"
echo "   Trigger: Git tags (v*) or manual dispatch"
echo "   Jobs: Verify → Build → Sign → Release"
echo "   Duration: ~30-40 minutes"
echo ""

echo "🔧 REQUIRED SETUP"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "1. Add GitHub Secret: GOOGLE_SERVICES_JSON"
echo "   Value: base64 encoded google-services.json"
echo "   Location: Settings → Secrets and variables → Actions"
echo ""
echo "   To encode (PowerShell):"
echo "   [Convert]::ToBase64String([IO.File]::ReadAllBytes('android/app/google-services.json')) | clip"
echo ""
echo "2. Optional: Add signing secrets for release workflow"
echo "   - SIGNING_KEY"
echo "   - SIGNING_KEY_ALIAS"
echo "   - KEY_STORE_PASSWORD"
echo "   - KEY_PASSWORD"
echo ""

echo "⌨️  LOCAL TESTING COMMANDS"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "npm run lint                    # Run ESLint"
echo "npx eslint --fix src/           # Auto-fix lint errors"
echo "npm test                        # Run Jest tests"
echo "npm run test:watch              # Jest watch mode"
echo "npm run test:coverage           # Generate coverage"
echo "npx tsc --noEmit                # Type check"
echo "npm audit                       # Check dependencies"
echo ""

echo "🚀 TRIGGERING WORKFLOWS"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "CI Pipeline (automatic):"
echo "  git push origin master"
echo ""
echo "Code Quality (automatic):"
echo "  Runs every Monday 9 AM UTC"
echo ""
echo "Release (from git tag):"
echo "  git tag -a v1.0.0 -m 'Release v1.0.0'"
echo "  git push origin v1.0.0"
echo ""
echo "Release (manual dispatch):"
echo "  GitHub Actions tab → Release Build → Run workflow"
echo ""

echo "📊 VIEWING RESULTS"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "1. Go to GitHub repository"
echo "2. Click 'Actions' tab"
echo "3. Select workflow run"
echo "4. Click job to view logs"
echo "5. Download artifacts"
echo ""

echo "🐛 TROUBLESHOOTING"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Problem: 'google-services.json not found'"
echo "→ Ensure GOOGLE_SERVICES_JSON secret is base64 encoded"
echo ""
echo "Problem: ESLint fails"
echo "→ Run 'npm run lint' locally, fix with 'npx eslint --fix'"
echo ""
echo "Problem: Tests fail"
echo "→ Run 'npm test' locally, add mocks to jest.setup.js"
echo ""
echo "Problem: APK build fails"
echo "→ Check secret encoding, verify android/app/build.gradle"
echo ""

echo "📚 DOCUMENTATION"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "📄 GITHUB_ACTIONS_SETUP.md       - Setup guide & overview"
echo "📄 CI_CD_SETUP.md                - Detailed CI/CD documentation"
echo "📄 .github/workflows/README.md   - Workflows reference"
echo "📄 GITHUB_ACTIONS_CHECKLIST.md   - Setup verification checklist"
echo ""

echo "⏱️  EXPECTED DURATIONS"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Lint Check:        5-10 minutes"
echo "Unit Tests:        10-15 minutes"
echo "APK Build:         20-30 minutes (first build longer)"
echo "Total CI:          40-50 minutes"
echo "Code Quality:      10-15 minutes"
echo "Release Build:     30-40 minutes"
echo ""

echo "💡 PRO TIPS"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "✓ Add '[skip ci]' to commit message to skip workflows"
echo "✓ Use semantic versioning for tags: v1.0.0, v1.0.1"
echo "✓ First APK build is slower (Gradle downloads dependencies)"
echo "✓ Tests can be auto-fixed with: npm run lint -- --fix"
echo "✓ Use GitHub branch protection to enforce CI checks"
echo ""

echo "✅ QUICK START"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "1. Configure GOOGLE_SERVICES_JSON secret on GitHub"
echo "2. git push origin master"
echo "3. Watch Actions tab"
echo "4. Fix any lint/test errors"
echo "5. Monitor APK build"
echo ""

echo "═══════════════════════════════════════════════════════════════════"
echo "For more info: Read GITHUB_ACTIONS_SETUP.md"
echo "═══════════════════════════════════════════════════════════════════"
