// ar.ts
export default {
  appName: 'تطبيق SOS',
  home: "الرئيسية",
  notifications: "التنبيهات",
  settings: 'الإعدادات',

  locationLogs: "سجل المواقع",

  Instructions: "التعليمات",
  InstructionsMessage: "يتم حفظ السجلات في كل مرة يتم فيها استلام تحديث للموقع، حتى في الخلفية أو عند إغلاق التطبيق.",
  noLogs: "لا توجد سجلات بعد. ابدأ التتبع!",
  noNotifications: "لا توجد تنبيهات بعد.",
  profileDetails: "تفاصيل الملف الشخصي",
  changeLanguage: "تغيير اللغة",
  version: "الإصدار",
  darkMode: "الوضع الداكن",
  toggleBetweenLightAndDarkTheme: "التبديل بين المظهر الفاتح والداكن",
  followSystem: "حسب إعدادات النظام",
  useSystemThemeSettings: "استخدام إعدادات مظهر النظام",
  appearance: "المظهر",
  about: "حول",
  battery: "البطارية",
  notificationPermissionDenied: "تم رفض إذن إظهار التنبيهات",
  testNotificationTitle: "تنبيه تجريبي",
  testNotificationBody: "هذا تنبيه تجريبي من شريط التطبيق.",
  addNotification: "إضافة إشعار",
  title: "العنوان",
  message: "الرسالة",
  status: "الحالة",
  save: "حفظ",
  cancel: "إلغاء",
  fieldRequired: "هذا الحقل مطلوب",

  bondCalculator: "حاسبة السندات",
  faceValue: "القيمة الاسمية",
  annualCouponRate: "معدل القسيمة السنوي (%)",
  marketPrice: "سعر السوق",
  yearsToMaturity: "عدد السنوات حتى الاستحقاق",
  couponFrequency: "تواتر القسيمة",
  annual: "سنوي",
  semiAnnual: "نصف سنوي",
  issueDate: "تاريخ الإصدار",
  calculate: "احسب",
  currentYield: "العائد الحالي",
  ytm: "العائد حتى تاريخ الاستحقاق (YTM)",
  totalInterest: "إجمالي الفائدة المكتسبة",
  premiumDiscount: "علاوة/خصم",
  cashFlowSchedule: "جدول التدفق النقدي",
  period: "الفترة",
  paymentDate: "تاريخ الدفع",
  couponPayment: "دفعة القسيمة",
  cumulativeInterest: "الفائدة التراكمية",
  remainingPrincipal: "أصل الدين المتبقي",
  premium: "علاوة",
  discount: "خصم",
  par: "متعادل"
};
