// ar.ts
export default {
  appName: 'Smart officer',
  accidentReconstruction: 'Accident reconstruction',
  accidentReconstructionTwoLines: 'Accident reconstruction',
  userName: 'آسم المستخدم',
  password: 'كلمة السر',
  login: 'تسجيل دخول',
  logout: 'تسجيل خروج',
  changeLanguage: 'تغيير اللغة',
  settings: 'الآعدادات',
  dismiss: 'dismiss',
  pleaseEnterUsername: 'Please enter username',
  pleaseEnterPassword: 'Please enter password',
  thePasswordShouldBeAtLeastSixCharacter:
    'The password should be at least 6 character',
  location: 'Location',
  plateNumber: 'Plate number',
  search: 'Search',
  licenseExpiry: 'License expiry',
  vehicle: 'Vehicle',
  color: 'Color',
  number: 'Number',
  licenseNumber: 'License number',
  time: 'Time',
  pleaseSelectALocation: 'Please select a location',
  pleaseSelectATime: 'Please select a time',
  primaryCause: 'Primary cause',
  accidentType: 'Accident type',
  roadCondition: 'Road condition',
  visibility: 'Visibility',
  numberOfCars: 'Number of cars',
  driverName: 'Driver name',
  driverNationality: 'Driver nationality',
  driverNumber: 'Driver number',
  yes: 'Yes',
  no: 'No',
  heTried: 'He tried',
  didTheDriverRunAway: 'Did the driver run away?',
  driverStatus: 'Driver status',
  unconscious: 'Unconscious',
  inPanic: 'In Panic',
  inShoke: 'In Shoke',
  injured: 'Injured',
  casualties: 'Casualties',
  numberOfInjury: 'Number of injury',
  name: 'Name',
  dob: 'Date of birth',
  nationality: 'Nationality',
  gender: 'Gender',
  female: 'Female',
  male: 'Male',
  car: 'Car',
  seatBelt: 'SeatBelt',
  wearing: 'Wearing',
  notWearing: 'Not-wearing',
  injuredIdentity: 'Injured identity',
  driver: 'Driver',
  passenger: 'Passenger',
  pedestrain: 'Pedestrain',
  injuredSeverity: 'Injured severity',
  minor: 'Minor',
  moderate: 'Moderate',
  serious: 'Serious',
  death: 'Death',
  reason: 'Reason',
  description: 'Description',
  accidentDrawing: 'Accident Drawing',
  previous: 'Previous',
  next: 'Next',
  submit: 'Submit',
  languages: 'Languages',
  profileDetails: 'Profile details',
  selectDatetime: 'Select datetime',
  attachments: 'Attachments',
  selectImageOrVideo: 'Select image or video',
  vehicleInformation: 'Vehicle Information',
  plotVehicleDamage: 'Plot vehicle damage',
  addNewVehicle: 'Add new vehicle',
  cancel: 'Cancel',
  update: 'Update',
  add: 'Add',
  close: 'close',
  save: 'save',
  driverInformation: 'Driver information',
  driverAdditionalInformation: 'Driver additional information',
  information: 'Information',
  vehicles: 'Vehicles',
  witnesses: 'Witnesses',
  drawing: 'Drawing',
  injuryDetails: 'Injury details',
  drivers: 'Drivers',
  accident: 'Accident',
  doYouWantToDeleteThisAttachment: 'Do you want to delete this attachment?',
  deleteAttachment: 'Delete attachment',
  searchBy: 'Search by',
  identity: 'Identity',
  passport: 'Passport',
  id: 'ID',
  numberOfWitness: 'Number of witness',
  statement: 'Statement',
  addNewDriver: 'Add new driver',
  addNewWitness: 'Add new witness',
  moreInformation: 'More information',
  attendance: 'Attendance',
  dashboard: 'Dashboard',
  tickets: 'Ticket',
  ticketsList: 'Tickets',
  tasks: 'Tasks',
  ticketsWithDriver: 'Tickets with driver',
  ticketsWithoutDriver: 'Tickets without driver',
  assignTask: 'Assign Task',
  vehicleDamage: 'Vehicle damage',
  accidentDetails: 'Accident details',
  addNewTicketWithDriver: 'Add New Ticket With Driver',
  confiscated: 'Confiscated',
  violation: 'Violation',
  addVehiclePlateNumber: 'Add vehicle plate number',
  retrieveVehicleInformation: 'Retrieve Vehicle Information',
  plateSource: 'Plate Source',
  vehicletype: 'Vehicle Type',
  carColor: 'Car Color',
  endDate: 'End Date',
  pleaseEnterPlateColor: 'Please Enter Plate Color',
  pleaseEnterVehcileType: 'Please Enter Plate Type',
  pleaseEnterPlateSource: 'Please Enter Plate Source',
  pleaseEnterPlatenumber: 'Please Enter Plate Number',
  pleaseEnterLicensenumber: 'Please Enter License Number',
  ticketImages: 'Ticket images',
  addDriverLicenseNumber: 'Add driver license number',
  retrieveLicenseInformation: 'Retrieve License Information',
  licenseSource: 'License Source',
  clear: 'Clear',
  confiscatedItems: 'Confiscated Items',
  vehicleImpounds: 'Vehicle impounds',
  vehicleImages: 'Vehicle images',
  impoundLocation: 'Impound location',
  driverImages: 'Driver images',
  driverDetained: 'Driver detained',
  ownerName: 'Owner Name',
  vehicleMakeModelColorYear: 'Make/Model/Color/Year',
  regExpiryDate: 'Reg.Expiry date',
  policyNumber: 'Policy number',
  insuranceCompany: 'Insurance company',
  insuranceExpiryDate: 'Insurance Expiry date',
  drivingLicense: 'Driving license',
  mobileNumber: 'Mobile number',
  dateOfBirth: 'Date of birth',
  tapOnTheButtonBelowToAddDriver: 'Tap on the button below to add driver',
  tapOnTheButtonBelowToAddVehicle: 'Tap on the button below to add vehicle',
  assets: 'Assets',
  licenseExpiryDate: 'Lic.Expiry date',
  licenseIssuePlace: 'License issue place',
  tapOnTheButtonBelowToAddWitness: 'Tap on the button below to add witness',
  tapOnTheButtonBelowToAddInjury: 'Tap on the button below to add injury',
  pleaseSelectOption: 'Please select option',
  carMake: 'Car make',
  carModel: 'Car model',
  year: 'Year',
  noVehicleMatchThisPlateNumber: 'No vehicle match this plate number',
  notes: 'Notes',
  comments: 'Comments',
  pleaseSelectDate: 'Please select a date',
  selectTicketType: 'Select ticket type',
  withDriver: 'With Driver',
  withoutDriver: 'Without Driver',
  violationTypes: 'Violation types',
  all: 'All',
  cautionary: 'Cautionary',
  fine: 'Fine',
  noDriverMatchThisPlateNumber: 'No driver match this plate number',
  addNewInjury: 'Add new injury',
  youHaveSubmittedTheTaskSuccessfully:
    'You have submitted the task successfully',
  road: 'road',
  select: 'Select',
  locationPicker: 'Location picker',
  pickALocation: 'Pick a location',
  affected: 'Affected',
  liable: 'Liable',
  notInjured: 'Not injured',
  ticketDetails: 'Ticket Details',
  ticketNumber: 'Ticket Number',
  addNewTicketWithoutDriver: 'Add New Ticket Without Driver',
  pleaseCheckYourInternetConnection: 'Please check your internet connection',
  direction: 'Direction',
  yourLocation: 'Your location',
  locationFieldIsRequired: 'Location field is required',
  delete: 'Delete',
  edit: 'Edit',
  pleaseEnterPolicyNumber: 'Please enter policy number',
  accidentLiability: 'Accident liability',
  areYouSureYouWantToDeleteThisVehicle:
    'Are you sure you want to delete this vehicle?',
  areYouSureYouWantToDeleteThisDriver:
    'Are you sure you want to delete this driver?',
  areYouSureYouWantToDeleteThisWitness:
    'Are you sure you want to delete this witness?',
  areYouSureYouWantToDeleteThisInjured:
    'Are you sure you want to delete this injured?',
  conscious: 'Conscious',
  unknownVehicle: 'Unknown vehicle',
  unknown: 'Unknown',
  severity: 'Severity',
  general: 'General',
  sign: 'Sign',
  punch: 'Punch',
  punchIn: 'Punch In',
  punchOut: 'Punch Out',
  roads: 'Roads',
  signs: 'Signs',
  welcomeTo: 'Welcome to',
  pleaseEnterUsernameAndPassword: 'Please enter username and password',
  addNewImage: 'Add new image',
  accidentImages: 'Accident images',
  rotate: 'Rotate',
  flip: 'Flip',
  doYouWantToDeleteThisScene: 'Do you want to delete this scene?',
  pleaseWait: 'Please wait an updated version is downloading.',
  updateAvailable: 'Update Available',
  updateMsg:
    'A new version of Smart Officer App is available which must be downloaded and installed',
  somethingwentworng: 'Something Went Wrong Please try again!',
  taskDetails: 'Task details',
  attendances: 'Attendances',
  welcomeBack: 'Welcome back',
  seeYouSoon: 'See you soon',
  doYouWantToPunchOut: 'Do you want to punch out ?',
  doYouWantToPunchIn: 'Do you want to punch in ?',
  filter: 'Filter',
  from: 'From',
  to: 'To',
  checkInMessage: 'Check in message',
  pleaseCheckInToStartYourWorkingHours:
    'Please check in to start your working hours',
  noDataFound: 'No data found',
  Injuries: 'Injuries',
  Assets: 'Assets',
  tapOnTheButtonBelowToAddAsset: 'Tap on the button below to add asset',
  addNewAsset: 'Add new asset',
  assetDetails: 'Asset details',
  degreeOfDamage: 'Degree of damage',
  assetImages: 'Asset images',
  totalWorkingHours: 'Total working hours',
  CHECK_IN: 'CHECK IN',
  CHECK_OUT: 'CHECK OUT',
  taskStatus: 'Task status',
  dueDate: 'Due date',
  rejected: 'Rejected',
  completed: 'Completed',
  type: 'Type',
  lastCheckIn: 'Last check in',
  detainedLocation: 'Detained location',
  camera: 'Camera',
  gallery: 'Gallery',
  remarks: 'Remarks',
  critical: 'Critical',
  high: 'High',
  low: 'Low',
  medium: 'Medium',
  date: 'Date',
  notifications: 'Notifications',
  details: 'Details',
  view: 'View',
  createTicketWithDriber: 'Create Ticket with driver',
  createTicketWithoutDriber: 'Create Ticket without driver',
  createTicket: 'Create Ticket',
  AddComments: 'Add comments',
  Refused: 'Refused',
  Open: 'Open',
  Timeline: 'Timeline',
};
