// ar.ts
export default {
  appName: 'Sos App',
  home: "Home",
  notifications: "Notifications",
  settings: "Settings",

  locationLogs: "Location Logs",
  Instructions: "Instructions",
  InstructionsMessage: "Logs are saved every time a location update is received, even in the background or when the app is closed.",
  noLogs: "No logs yet. Start tracking!",
  noNotifications: "No notifications yet.",
  profileDetails: "Profile Details",
  changeLanguage: "Change Language",
  version: "Version",
  darkMode: "Dark Mode",
  toggleBetweenLightAndDarkTheme: "Toggle between light and dark theme",
  followSystem: "Follow System",
  useSystemThemeSettings: "Use system theme settings",
  appearance: "Appearance",
  about: "About",
  battery: "Battery",
  notificationPermissionDenied: "Permission to show notifications was denied",
  testNotificationTitle: "Test Notification",
  testNotificationBody: "This is a test notification from the app bar.",
  addNotification: "Add Notification",
  title: "Title",
  message: "Message",
  status: "Status",
  save: "Save",
  cancel: "Cancel",
  fieldRequired: "This field is required"
};
